### PR TITLE
scene,api: allow aspect ratio to be set to 0

### PR DESCRIPTION
**Pull request by mbouron**
Setting the aspect ratio to 0 allows the main viewport dimensions to match the output window/surface dimensions. This is particularly useful if one wants to render to the whole window/surface and do not want nope.gl to manage the aspect ratio.

### CODE REVIEW

**Review by ubitux — COMMENTED** [review]
What happens in case of a resize?

**Comment by mbouron** [comment]
> What happens in case of a resize?

The viewport is automatically computed to match the new window/surface dimensions.

**Review by ubitux — APPROVED** [review]
Should be OK, but I'd be more comfortable with a test.

Does it work correctly with node that use the aspect ratio?

**Comment by mbouron** [comment]
> > What happens in case of a resize?
> 
> The viewport is automatically computed to match the new window/surface dimensions.

Good point. Added commits so the player and cmp module handle the aspect ratio being set to 0 plus a test that exercises text rendering in such scenario.

**Review by ubitux — APPROVED** [review]

**Pull request merged**
